Repository caddyserver/website, pull requests merged in 2022-05, with the labels that each got.

#232 logos: In dark mode, use invert + hue-rotate
  src/resources/css/docs.css
Labels: bug

#231 docsearch: Upgrade to v3
  src/includes/footer.html
  src/includes/head.html
  src/includes/header-nav.html
  src/resources/css/common.css
  src/resources/css/docs.css
  src/resources/js/common.js
Labels: enhancement

#230 css: Rework how paper is positioned
  src/resources/css/docs.css
Labels: bug

#233 json: Make URL #fragment jump to the right spot after loading
  src/resources/js/json-docs.js
Labels: bug

#219 docs: Fix Debian installation instructions
  src/docs/markdown/install.md
  src/resources/css/docs.css
Labels: bug

#228 docs: Changes for v2.5.1 release
  src/docs/markdown/caddyfile/concepts.md
  src/docs/markdown/caddyfile/directives.md
  src/docs/markdown/caddyfile/directives/forward_auth.md
  src/docs/markdown/caddyfile/directives/log.md
  src/docs/markdown/caddyfile/directives/php_fastcgi.md
  src/docs/markdown/caddyfile/directives/redir.md
  src/docs/markdown/caddyfile/directives/reverse_proxy.md
  src/docs/markdown/caddyfile/matchers.md
  src/docs/markdown/caddyfile/patterns.md
Labels: documentation
